easy_admin:
    list:
        title: '%%entity_label%% listing'
        max_results: 30
        actions:
            # displays both the action label and a custom icon
            - { name: 'edit', icon: 'pencil', label: false, title: 'Edit'  }
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    #site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    site_name: 'Test <em style="font-size: 80%;">EsyAdmin</em>'
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            label: 'Products'
            help: 'Global message displayed in all views'
            list:
                title: '%%entity_label%% listing'
                help: 'The list view overrides the global help message'
                max_results: 10
                fields: ['id', { property: 'name', label: 'First name' }, 'price']
            # Doctrine associations are also supported in the 'search' view. This config looks
            # for data in the 'email' and 'phone' properties of the associated 'user' entity
            search:
                fields: ['id', 'name', 'price']
        Category:
            class: App\Entity\Category
            label: 'Categories'
       # - App\Entity\User

    design:
        #menu:
        #    #- { label: 'Inventory' }
        #    - label: 'Inventory'
        #      children: ['Product', 'Category']

        menu:
            - label: 'Products'
              icon: 'users'
              children:
                #- { label: 'New Invoice', icon: 'file-new', route: 'createInvoice' }
                #- { label: 'Invoices', icon: 'file-list', entity: 'Invoice' }
                #- { label: 'Payments Received', entity: 'Payment', params: { sortField: 'paidAt' } }
                  - { label: 'Categories', icon: 'object-group', entity: 'Category' }
                  - { label: 'Products', icon: 'cubes', entity: 'Product' }
            - label: 'About'
              children:
                #- { label: 'Help', route: 'help_index' }
                  - { label: 'Docs', url: 'http://example.com/external-docs' }
                #  - { label: '%app.version%' }

        brand_color: '#1ABC9C'

        # the value of this option can be any valid CSS color
        # brand_color: 'red'
        # brand_color: 'rgba(26, 188, 156, 0.85)'

        # if the color includes a '%', you must double it to escape it in the YAML file
        # brand_color: 'hsl(0, 100%%, 50%%);'
        #assets:
        #    css:
                # ...
        #        - '/bundles/easyadmin/stylesheet/easyadmin-all.min.css'
        #    js:
        #        - '/bundles/easyadmin/javascript/easyadmin-all.min.js'
